- .github/workflows/deploy.yml
> [DEV-41] chore: CI/CD환경 구축 (s3,cloudfront 연동)

- src/index.css
- 정확한 Spoqa Han Sans Neo 폰트 재설정
> [DEV-61] fix: 폰트 재설정

- package.json
- public/mockServiceWorker.js
- src/Router.tsx
- src/components/common/contentCard/ContentCard.tsx
- src/components/header/Header.tsx
- src/main.tsx
- src/mocks/browser.ts
- src/mocks/data/contentCard.ts
- src/mocks/handlers.ts
- src/pages/DashBoard.tsx
- src/pages/Home.tsx
- src/types/interface.ts
- yarn.lock
- Dashboard -> Home이름 변경
- Home ui 작성
- msw 세팅
- 인터페이스 파일 작성 (필드 내용 확정 X )
> [DEV-62] Feat: Home UI, MSW 세팅

- src/components/common/contentCard/ContentCard.tsx
- src/main.tsx
- 배포환경에서도 msw 활성화하도록 수정
- ContentCard 컴포넌트 tag부분 레이아웃 수정
> [DEV-66] hotfix: msw 배포 환경 활성화

- src/components/common/contentCard/KeywordTags.tsx
- src/components/common/home/contents/latest/HomeLatestContentSkeleton.tsx
- src/components/common/home/contents/latest/HomeLatestcontent.tsx
- src/components/common/home/contents/popular/HomePopularContents.tsx
- src/components/common/home/contents/popular/HomePopularcontentsSkeleton.tsx
- src/hooks/homeContent/useHomeContentsQuery.ts
- src/pages/Home.tsx
- src/services/authApi.ts
- src/services/contentAPi.ts
- src/services/homeContentApi.ts
- src/services/scrapApi.ts
- src/types/interface.ts
- 홈 페이지 ui, skeletion ui 작성
- 백엔드와 연동
> [DEV-62] Feat: Home UI 작성, 연동

- package.json
- src/Router.tsx
- src/components/contentList/ContentListCard.tsx
- src/components/contentList/ContentListSkeleton.tsx
- src/components/contentList/Observer.tsx
- src/hooks/contentList/useContentListQuery.ts
- src/pages/ContentList.tsx
- src/services/contentListApi.ts
- src/services/homeContentApi.ts
- src/types/interface.ts
- yarn.lock
의존성 추가 
```
yarn add react-intersection-observer --save
```
- 컨텐츠 목록 ui작성, 연동
- homeContentApi 수정
> [DEV-75] Feat: 컨텐츠 목록 페이지 ui, 연동

- src/components/common/LoginModal.tsx
- src/store/useLoginModalStore.ts
- 로그인 모달 전역상태 생성 [useLoginModalStotre.ts]
> feat: 로그인 모달 전역상태 생성

- package.json
- src/components/common/LoginModal.tsx
- yarn.lock
- 라이브러리 설치시 리액트 버전과 충돌이 일어나 직접 모달 구현
> horfix: 리액트 모달 라이브러리 제거

- .github/workflows/deploy.yml
- index.html
- package.json
- src/App.tsx
- src/hooks/common/useTrackRoute.ts
- yarn.lock
- react-ga4 패키지 설치
- 라우트가 변경됨을 추적하는 커스텀훅 useTrackRoute 생성
- deploy.yml에 ga ID 추가 및 깃허브 액션 시크릿에 추가 완료
- index.html seo개선하기 위한 헤드 태그 description, author, keywords 과 canonical URL 추가
> [DEV-97] GA 연동 및 SEO 개선

- index.html
- src/App.tsx
- src/components/common/TrackRoute.tsx
- route 추적하는 커스텀 훅이 아닌 tsx컴포넌트로 변경
> hotfix: 커스톰훅이 아닌 tsx 컴포넌트로 변경

- src/hooks/contentDetail/useContentDetails.ts
- src/hooks/contentDetail/useScrappedState.ts
- src/hooks/homeContent/useMyViewCount.ts
- src/hooks/myScrap/useScrapModalHandlers.ts
This reverts commit 85d7dceb29b35ca63acbd0bc618702f69ee0a4c1.
> Revert "refactor: camelCase 파일명 수정 (contentAPi -> contentApi)"

- src/components/contentDetail/ScriptWithTime.tsx
- src/components/contentDetail/Tooltip.tsx
- src/components/myScrap/keyword/PlayImgBtn.tsx
- src/components/myScrap/keyword/ScrapedTermCard.tsx
- src/components/myScrap/keyword/ScrapedTerms.tsx
- src/components/myScrap/keyword/ViewAgainBtn.tsx
- src/handlers/contentDetail/handleToolTip.ts
- src/hooks/contentDetail/useScrollToElement.ts
- src/hooks/contentDetail/useTooltip.ts
- src/pages/ContentDetail.tsx
- src/types/interface.ts
- 마이페이지에서 용어 다시 보기 클릭시 상세 페이지로 이동하여 오토스크롤링 구현
- 상세페이지, 툴팁 상태 관리 이슈 해결
> [DEV-140] 오토스크롤링 구현 및 툴팁 상태관리 이슈 해결

- src/store/useContentStore.ts
- 콘텐츠 상세 페이지에서 콘텐츠 id의 초기화값을 0으로 수정
> fix: 콘텐츠 id 초기화값 수정

- src/components/common/Button.tsx
- src/components/common/header/Header.tsx
- src/components/contentDetail/ScriptWithTime.tsx
- 콘텐츠 모으러 가기 버튼, 용어 모으러 가기 버튼 gtm과 연결할 id생성
- 헤더에 콘텐츠 목록 링크 gtm과 연결할 id 생성
- 스크랩할 용어 gtm과 연결할 id 생성
> [DEV-97]feat: gtm link

- src/hooks/contentDetail/useTooltip.ts
- 콘텐츠 상세 페이지 스크랩 상태를 불필요하게 관리 하는 것을 제거
> hotfix: 불필요한 상태관리 제거

- src/styles/styles.css
- 모바일에서도 checkbox의 rounded를 제거
> design: checkbox roundeded 제거

- src/index.css
- input의 webkit appearance, border-radius 제거
> design: input의 webkit appearance, border-radius 제거

- src/components/contentDetail/ScriptWithTime.tsx
- 비로그인시 dictionaryId가 undefined로 나와 id로 하면 ununique해져 class로 변경
> fix: mark id 매칭 id에서 className으로 변경

- src/components/contentDetail/ScrapAndShare.tsx
- src/hooks/contentDetail/useScrapAndShare.ts
- 콘텐츠 스크랩 gtm 이벤트 커스텀 위한 스크랩 버튼에 id생성
> [DEV-188] feat: 콘텐츠 스크랩 gtm 이벤트 커스텀 위한 스크랩 버튼에 id생성

- src/components/contentDetail/ScriptWithTime.tsx
- GTM 태그를 등록하기 위해 mark의 id값을 변경한 것을 롤백
> [DEV-190] fix: 오토 스크롤링 위한 mark의 id값 변경

- src/components/contentDetail/ScriptWithTime.tsx
- src/components/myScrap/DesktopMenu.tsx
- src/components/myScrap/MenuWithUnderbar.tsx
- 타임스탬프 버튼 클릭
- 마이스크랩 > 콘텐츠 탭 클릭
- 마이스크랩 > 단어장 탭 클릭
> [DEV-196] feat: gtm 태그 클릭 이벤트 위해 id 연결

- src/components/contentDetail/VideoPlayer.tsx
- src/pages/ContentDetail.tsx
- src/utils/contentDetailUtils.ts
: 영상 재생 시간에 맞춰 해당하는 타임스탬프가 있는 스크립트가 상단으로 오토 스크롤링
> feat: 타임 스탬프 고도화

- src/components/contentDetail/Tooltip.tsx
- 스크랩 하기 button에 scrap-term id 생성
> feat: gtm 용어 스크랩 이벤트 등록하기 위한 id 매칭

- src/components/common/Layout.tsx
- src/hooks/contentDetail/useScrollToElement.ts
- src/index.css
- 전체 페이지내 y-scroll 적용
- 용어 오토스크롤링 데스크롭에서 안정화 완료 하지만 스크롤링 블링킹 이슈 발생중
> fix: 데스크톱 용어 오토스크롤링 안정화 

- src/hooks/contentDetail/useScrollToElement.ts
- 모바일/태블릿 과 데스크톱 스크롤 동작이 달라 다르게 동작하게 구현
> fix: 데스크톱과 그 외 환경 오토 스크롤링 동작 구분

- src/components/contentDetail/VideoPlayer.tsx
- src/hooks/contentDetail/useVideoScriptSync.ts
- src/pages/ContentDetail.tsx
- src/types/interface.ts
- 디바이스 크기에 맞게 스크롤링 위치 선정
- 코드 리팩토링
> fix: 영상 속도에 맞춰 스크립트 오토 스크롤링

- index.html
- robots.txt
- 메타 설명 태그 80자 내외로 수정
- 메타 키워드 태그 서비스 이름 추가
- 메타 og 설명, title 추가 및 이미지는 디자인팀에서 전달 예정
- 크롤링 가능하게 robots.txt 추가
> [DEV-215] seo 개선

- src/Router.tsx
> refactor:code splitting 취소

- src/components/contentDetail/ShareModal.tsx
- src/hooks/contentDetail/logic/useShareModalLogic.ts
- 공유 모달 비지니스 로직 및 ui 로직 분리
- 공유 관련 아이콘 이미지 preload
> refactor: 콘텐츠 상세 페이지 리팩토링

- src/components/dashboard/Onboarding.tsx
- src/components/myWordList/ExplanationModal.tsx
- src/constants.ts
- tailwind.config.js
- 해석에 mock 데이터 추가
- 온보딩 ui shadow추가
> fix: qa 위해 mock data 추가

- src/components/myWordList/ProfileSection.tsx
- src/components/myWordList/WordList.tsx
- src/hooks/myWordList/api/useAddKeyNote.ts
- src/hooks/myWordList/api/useDeleteKeyNote.ts
- 토스트와 용어 노트간 이동 타이밍 조절
- 툴팁 여부에 따른 공백 적용 제거
-  news-list로 경로 변경
- 프로필 섹션 flex 적용
> fix: 나의 단어장 페이지 qa따른 변경

- src/components/myWordList/WordList.tsx
- src/hooks/myWordList/api/useGetWordListData.ts
- src/hooks/myWordList/useGetWordList.ts
- src/hooks/myWordList/useWordList.ts
- 나의 단어장 리스트내  항상 최신 데이터를 가져오도록 강제하도록 staleTime:1000으로 설정
- 중복 계산 방지하기 위해 메모제이션 적용
> fix: 나의 단어장 페이지 중복 계산 방지하기 위해 메모제이션 적용

- src/components/common/Keywords.tsx
- src/components/dashboard/Onboarding.tsx
- src/components/myWordList/Tutorial/TutorialModal.tsx
- src/components/myWordList/WordList.tsx
- src/components/myWordList/Words/EmptyWordState.tsx
- src/components/myWordList/Words/WordListContent.tsx
- src/hooks/common/useDisableScroll.ts
- src/hooks/dashboard/useOnboarding.ts
- src/hooks/myWordList/useWordList.ts
- src/hooks/myWordList/useWordListContentLogic.ts
- src/types/interface.ts
- 모달이 띄어졌을 때 전체 스크롤 비활성하는 커스텀 훅 생성
-  온보딩 이미지 사이즈 롤백
- 홈 페이지 툴팁 잔상 문제 해결
- 나의 단어장 페이지 오답노트, 졸업 노트미 렌더링 해결
- 나의 단어장 페이지 리팩토링
> fix: 홈 페이지, 나의 단어장 페이지 qa에따른 변경

- src/index.css
This reverts commit 8eb083bf9946154941c052c1376e672422a5c2e3.
> Revert "fix: 그림자 잔상 이슈 해결하기 위해 body태그에  -webkit-transform: translateZ(0)추가"

- src/components/myWordList/MyWordListNavBar.tsx
- src/components/myWordList/Words/WordListContent.tsx
- src/pages/MyWordList.tsx
- 구분 블럭 중앙 정렬
- 단어장 리스트 key 값 변경
> design: 나의 단어장 페이지 오류 수정

- src/components/dashboard/Banner.tsx
- src/components/myWordList/ProfileSection.tsx
- src/constants/constants.ts
- src/constants/queryKeys.ts
- src/hooks/dashboard/useBanner.ts
- src/hooks/myWordList/api/useAddKeyNote.ts
- src/hooks/myWordList/api/useDeleteKeyNote.ts
- src/hooks/myWordList/api/useGetWordListData.ts
- src/hooks/myWordList/api/useLearningStatus.ts
- src/hooks/myWordList/useProfileSectionLogic.ts
- src/hooks/newDetail/useRemoveScrapWord.ts
- src/hooks/newDetail/useScrapWord.ts
- src/hooks/newsList/useNewsListLogic.ts
- src/pages/NewsList.tsx
- src/types/interface.ts
- src/utils/dashboardUtils.ts
- 퀴즈 배너 로그인 모달 뒤로가기 제거
- footer FAQ 삭제 및 오류 접수 경로 변경
[나의 단어장 페이지]
- refetch대신 invalidQueries 필요시 invalidQueries 로 사용
- 퀴즈 활성화 오답 노트수 고려해 변경
> refactor: 나의 단어장 페이지 리팩토링

- src/hooks/myWordList/api/useLearningStatus.ts
- 히스토리 쿼리키 통일하기 위해 "getHistory" -> "히스토리"로 변경
> fix: 히스토리 쿼리키 히스토리로 변경

- src/hooks/myWordList/api/useLearningStatus.ts
- src/hooks/myWordList/useFirstLogin.ts
- 기존 튜토리얼 확인 키"hasSeenTutorial" 제거하고 새로운 키 "isTutorialCompleted" 생성
> [fix] 나의 단어장 튜토리얼 local storage 키 변경

- src/Router.tsx
- src/hooks/dashboard/useDashboard.ts
- src/hooks/dashboard/useLatestNews.ts
- src/hooks/dashboard/usePopularNews.ts
- src/pages/Dashboard.tsx
- src/pages/MyWords.tsx
- src/services/DashboardApi.ts
- 홈 페이지 주간 인기 뉴스 api 바인딩 인기 뉴스 -> "주간 인기 뉴스" 제목 변경
- 나의 단어장 페이지 롤백, 첫 퀴즈 여부 제거
> [feat] 홈 페이지 주간 인기 뉴스 api 바인딩

- src/components/common/Keywords.tsx
- src/components/common/NewsCard.tsx
> fix: 홈 페이지 툴팁 위치 조정

- index.html
- src/main.tsx
이전 PR #286에서 parytown을 적용하는 데 문제를 발견해 수정하였습니다. 하지만 local에서는 cors 오류를 발생해 배포 사이트에서 확인 후 문제가 지속되면 partytown를 제거하도록 하겠습니다.
> [fix] gtm 코드에 parytown 적용

- src/components/myWordList/Tutorial/TutorialModal.tsx
- src/hooks/common/useDisableScroll.ts
- src/hooks/dashboard/useOnboarding.ts
useDisabledScrolled에 조건 추가해 모달 팝업시에만 스크롤 막기로 구현
> fix: useDisabledScroll 조건 추가
